"""Contains the base class for :class:`PinCtrl`."""
import ioc
from sq.ctrl import EndpointCtrl

class BasePinCtrl(EndpointCtrl):
    """Generated by SG to serve as an abstract base class for:

        safi.app.ctrl.PinCtrl

    This class encapsulates external dependencies (such as the inversion-of-control
    requirements) and specifies the interface for the concrete implementation.
    """
    pin = ioc.class_property('PinService')

    async def post(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`PinCtrl.post()`
        and should be implemented in the following file:

            ./safi/ctrl/pin/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")


#pylint: skip-file
# !!! SG MANAGED FILE -- DO NOT EDIT -- VERSION:  !!!
