---
#######################################################################
#
# SAFI SYSTEM COMPOSE FILE
#
# This Docker Compose configuration file sets a Docker network
# resembling the production system environment hosting the
# application.
#
# In addition to the environment variables recognized by the
# application, the following variables configure the behavior of the
# spawned containers:
#
# SAFI_HTTP_PORT:
#   Specifies the port to which the HTTP server binds (default: 8443).
# SAFI_RDBMS_PORT:
#   Specifies the port to which the Relational Database Management
#   System (RDBMS) binds.
# SAFI_AMQP_PORT:
#   Specifies the port to which the Aorta backend binds (default: 5672).
#   Consumers may connect to this port in order to *receive* messages
#   published in the system.
# SAFI_MQADM_PORT:
#   Specifies the port to which the administrative web interface of
#   the message broker backend binds (default: 8161).
#
#######################################################################
version: '3'
services:
  safi_migrations:
    build: .
    environment:
    - SAFI_RUNTIME=migrations
    - SAFI_SECRET_KEY=a4f82ec9800ba3ae40a51717ffb2da128db4f0b25e2f30730c688ccb8e250892
    - SAFI_RDBMS_DSN=postgresql+psycopg2://safi:safi@rdbms:5432/safi
    depends_on:
    - rdbms
  safi:
    build: .
    environment:
    - SAFI_RUNTIME=${SAFI_RUNTIME-service}
    - SAFI_SECRET_KEY=a4f82ec9800ba3ae40a51717ffb2da128db4f0b25e2f30730c688ccb8e250892
    - SAFI_RDBMS_DSN=postgresql+psycopg2://safi:safi@rdbms:5432/safi
    depends_on:
    - rdbms
    volumes:
    - "./etc:/etc/safi:ro"
    expose:
    - "8443"
  http:
    image: nginx:1.15.0-alpine
    volumes:
    - "./etc/certs/snakeoil.crt:/etc/ssl/certs/snakeoil.crt:ro"
    - "./etc/private/snakeoil.pem:/etc/ssl/private/snakeoil.pem:ro"
    - "./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
    - "127.0.0.1:${SAFI_HTTP_PORT-8443}:443"
  rdbms:
    image: postgres:10.3-alpine
    restart: always
    environment:
    - POSTGRES_DB=safi
    - POSTGRES_USER=safi
    - POSTGRES_PASSWORD=safi
    expose:
    - 5432
    ports:
    - "127.0.0.1:${SAFI_RDBMS_PORT-5432}:5432"
