"""Contains the base class for :class:`AuthenticationCtrl`."""
from sq.ctrl import EndpointCtrl

class BaseAuthenticationCtrl(EndpointCtrl):
    """Generated by SG to serve as an abstract base class for:

        safi.app.ctrl.AuthenticationCtrl

    This class encapsulates external dependencies (such as the inversion-of-control
    requirements) and specifies the interface for the concrete implementation.
    """

    async def post(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`AuthenticationCtrl.post()`
        and should be implemented in the following file:

            ./safi/ctrl/authentication/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")


#pylint: skip-file
# !!! SG MANAGED FILE -- DO NOT EDIT -- VERSION:  !!!
