---
relations:
- relname: pin
  classname: PIN
  description: >
    Stores a Personal Identification Number (PIN) and tracks the failed
    attempts.
  columns:
  - name: gsid
    primary_key: true
    type: uuid
    description: >
      Specifies the Global Subject Identifier (GSID), uniquely
      identifying a Subject within the boundaries of a Quantum
      system.
  - name: pin
    type: string
    description: >
      The Personal Identification Number (PIN).
  - name: failed
    type: int32
    default:
      type: literal
      value: "0"
    description: >
      Maintains the number of failed attempts. The system may choose to block
      a PIN code if the number of failed attempts exceeds an arbitrary limit.
      This counter is reset on succesful PIN authentication.
  - name: last_used
    type: int64
    default:
      type: literal
      value: "0"
    description: >
      Specifies the date/time at which the PIN was last used, in milliseconds
      since the UNIX epoch. This also registers failed attempts.

- relname: onetimepasswords
  classname: OneTimePassword
  description: >
    Stores AES-256 GCM encypted shared secrets for Subjects maintained
    by a Quantum system.
  fixtures:
  - gsid: 00000000-0000-0000-0000-000000000000
    nsid: test@quantumframework.org
    generated: 1532636411233
    kind: T
    secret: bc35a790bde46cd4569597cd0000000000000000581af7b130a3bb03c8fdfabb98d3c23546689530397fa72bb6b379176fd227f7
    counter: 30
    issuer: SAFI Test Case
  columns:
  - name: gsid
    primary_key: true
    type: uuid
    description: >
      Specifies the Global Subject Identifier (GSID), uniquely
      identifying a Subject within the boundaries of a Quantum
      system.
  - name: nsid
    type: string
    description: >
      Specifies the Natural Subject Identifier (GSID), naturaly
      identififying the Subject. This identifier is used for
      display purposes in client applications only.
  - name: generated
    type: int64
    description: >
      The date/time at which the One-Time Password (OTP) was generated,
      in milliseconds since the UNIX epoch.
  - name: kind
    type: string
    description: >
      Declares the type of OTP. Allowed values are C(ounter) or
      T(ime-based).
    choices: [C,T]
    default:
      type: string
      value: T
  - name: secret
    type: string
    description: >
      A hex representation of the AES-256 encrypted shared secret.
  - name: counter
    type: int32
    description: >
      For counter-based OTPs, the current counter value. For time-based
      OTPs, the interval.
  - name: issuer
    type: string
    description: >
      A human-readable description of the OTP issuer.
  - name: enabled
    type: boolean
    default:
      type: literal
      value: "False"
    description: >
      Indicates if the TOTP is enabled for this **Subject**.
