---
#######################################################################
# OpenAPI definition for the  application.
#
# NOTES:
#
# - Endpoints are configured with the `x-endpoint` attribute.
# - Schema definitions of `requestBody`, for any content type,
#   is assumed to be defined in `components` and referenced.
#
#######################################################################
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Subject One-Time Password Service
  description: >
    This service exposes an API to generate, refresh, remove and verify
    One-Time Passwords (OTPs) for Subjects in a Quantum system.
  termsOfService: https://www.wizardsofindustry.net
  contact:
    name: Cochise Ruhulessin
    url: https://www.wizardsofindustry.net/projects/quantum
    email: cochise.ruhulessin@wizardsofindustry.net
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: http://safi.dev.quantumframework.org:8443
  description: Local development server
- url: https://citadel.dev.quantumframework.org/safi
  description: Local development server (Citadel)
paths:
  /health/:
    summary: Reports the general health of the application.
    x-endpoint:
      classname: HealthEndpoint
      controller:
        qualname: sq.ext.health.HealthCheckCtrl
    parameters:
    - name: timeout
      in: query
      description: Specifies the timeout of the health-check, in milliseconds.
      schema:
        type: integer
    get:
      operationId: get_health
      responses:
        200:
          description: The service is functioning normally.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /version:
    summary: Reports the currently running version of the application.
    x-endpoint:
      classname: VersionEndpoint
      controller:
        qualname: sq.ext.health.VersionCtrl
    get:
      operationId: get_version
      responses:
        200:
          description: Details about the current application deployment.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /generate/pin:
    summary: >
      Provides an interface to create or regenerate the Personal Identification
      Number (PIN) for the Subject identified in the request entity.
    x-endpoint:
      classname: PinEndpoint
      controller:
        qualname: safi.app.ctrl.PinCtrl
    post:
      operationId: createotp
      summary: Generate a new PIN for the Subject identified in the request entity.
      requestBody:
        description: >
          This endpoint expects the Global Subject Identifier (GSID) to be present
          in the request payload.
        content:
          application/json:
            schema:
              required:
              - gsid
              properties:
                gsid:
                  type: string
                  format: uuid
      responses:
        201:
          description: >
            A new PIN is generated for the identified Subject.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SharedSecret"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /generate/otp:
    summary: >
      Provides an interface to create or regenerate the One-Time Password (OTP)
      for the Subject identified in the request entity.
    x-endpoint:
      classname: OneTimePasswordEndpoint
      controller:
        qualname: safi.app.ctrl.OneTimePasswordCtrl
    post:
      operationId: createotp
      summary: Generate a new OTP for the Subject identified in the request entity.
      requestBody:
        description: >
          This endpoint expects the Global Subject Identifier (GSID), the Issuer
          name and a Natural Subject Identifier (NSID) to be present in the
          request body.
        content:
          application/json:
            schema:
              required:
              - gsid
              - nsid
              - issuer
              properties:
                gsid:
                  type: string
                  format: uuid
                nsid:
                  type: string
                issuer:
                  type: string
      responses:
        201:
          description: >
            A new OTP is generated for the identified Subject.
          content:
            image/png:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                $ref: "#/components/schemas/SharedSecret"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /verify/{kind}:
    summary: >
      Verifies a One-Time Password (OTP) for a Subject.
    x-endpoint:
      classname: VerificationEndpoint
      controller:
        qualname: safi.app.ctrl.VerificationCtrl
    parameters:
    - name: kind
      in: path
      description: >
        Specifies the type of OTP (totp hotp).
      required: true
      schema:
        type: string
    post:
      operationId: verify
      requestBody:
        description: >
          This endpoint expects the Global Subject Identifier (GSID) and
          a One-Time Password (OTP) to be present in the request body.
        content:
          application/json:
            schema:
              required:
              - gsid
              - code
              properties:
                gsid:
                  type: string
                  format: uuid
                code:
                  type: string
      responses:
        200:
          description: >
            An OTP exists for the Subject identified in the request entity
            and the provided value was correct.
        401:
          description: >
            An OTP exists for this Subject but the value provided in the
            request entity did not match.
        403:
          description: >
            An OTP exists for this Subject but it has been blocked for
            use as an authentication mechanism.
        404:
          description: >
            The Subject identified in the request entity does not
            exist.
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /subject/{gsid}/challenge:
    summary: >
      Retrieve the Factors that may be used for interim authentication
      challenges.
    x-endpoint:
      classname: SubjectChallengesEndpoint
      controller:
        qualname: safi.app.ctrl.SubjectChallengeCtrl
    parameters:
    - name: gsid
      in: path
      required: true
      schema:
        type: string
        format: uuid
    get:
      operationId: get_challenge_methods
      summary: >
        Retrieve the Factors that may be used for interim authentication
        challenges.
      responses:
        200:
          description: >
            One or more Factors were configured for the Subject identified
            in the request URI and are usable for interim authentication
            challenges.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  enum:
                  - otp
                  - password
                  - pin
                  - puk
                  - u2f
        404:
          description:
            No Factors were configured for the Subject identified in the
            request URI or existing Factors are not usable as interim
            authentication challenges. The array contained in the response
            body is always empty.
          content:
            application/json:
              schema:
                example: []
                type: array
                items:
                  type: string
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /authenticate:
    summary: >
      Authenticates a Subject based on the authentication factors contained in
      the request entity.
    x-endpoint:
      classname: AuthenticationEndpoint
      controller:
        qualname: safi.app.ctrl.AuthenticationCtrl
    post:
      operationId: authenticate
      requestBody:
        description: >
          Deserialize the authentication factors from the request payload and
          establish the identity of the Subject specified by `gsid`.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MultiFactor"
      responses:
        200:
          description: >
            The Factors contained in the request payload were valid and succesfully
            established the identity of the specified Subject.
        401:
          description: >
            The Factors could not establish the identity of the Subject
        403:
          description: >
            The Factors established the identity of the Subject, but it has been
            barred from authenticating.
        404:
          description: >
            The Subject identified in the request entity does not
            exist.
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"


components:
  responses:
    ServiceNotAvailable:
      description: One or more (upstream) dependencies is not available.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ServiceNotAvailable"

    UncaughException:
      description: An uncaught exception condition interrupted the request-response cycle.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Factor:
      description: >
        Describes the authentication Factor specified by `using` for the
        Subject identified by `gsid`.
      type: object
      nullable: false
      oneOf:
      - $ref: "#/components/schemas/OneTimePasswordFactor"
      - $ref: "#/components/schemas/PersonalIdentificationNumberFactor"
      discriminator:
        propertyName: using
        mapping:
          otp: "#/components/schemas/OneTimePasswordFactor"
          pin: "#/components/schemas/PersonalIdentificationNumberFactor"
      required:
      - gsid
      - using
      properties:
        gsid:
          description: >
            A Global Subject Identifier (GSID) specifying the Subject to which
            this Factor is applicable.
          type: string
          format: uuid
        using:
          description: >
            Specifies the type of authentication factor that is contained in the
            Factor object.
          type: string
          enum:
          - otp
          - password
          - pin
          - puk
          - u2f

    PersonalIdentificationNumberFactor:
      description: >
        Describes a Personal Identification Number (PIN) factor for the Subject
        identified by `gsid`.
      type: object
      nullable: false
      example:
        using: pin
        gsid: "00000000-0000-0000-0000-000000000000"
        factor: "1234"
      required:
      - factor
      properties:
        factor:
          description: >
            The Personal Identification Number (PIN) provisioned to the
            Subject.
          type: integer
          format: int32
          nullable: false

    OneTimePasswordFactor:
      description: >
        Describes a One-Time Password (OTP) factor for the Subject
        identified by `gsid`.
      type: object
      nullable: false
      example:
        using: otp
        gsid: "00000000-0000-0000-0000-000000000000"
        factor: "123456"
      required:
      - factor
      properties:
        factor:
          description: >
            The One-Time Password (OTP) generated by the client application
            based on the shared secret.
          type: integer
          format: int32
          nullable: false

    PinUnlockKeyFactor:
      description: >
        Describes a PIN Unlock Key (PUK) factor for the Subject
        identified by `gsid`.
      type: object
      nullable: false
      example:
        using: otp
        gsid: "00000000-0000-0000-0000-000000000000"
        factor: "12345678"
      required:
      - factor
      properties:
        factor:
          description: >
            The PIN Unlock Key (PUK) that the Subject may provide to unlock
            a blocked Personal Identification Number (PIN).
          type: integer
          format: int32
          nullable: false

    PasswordFactor:
      description: >
        Describes a generic password factor for the Subject
        identified by `gsid`.
      type: object
      nullable: false
      example:
        using: password
        gsid: "00000000-0000-0000-0000-000000000000"
        factor: "the quick yellow penguin slid in the lazy dogs dms"
      required:
      - factor
      properties:
        factor:
          description: >
            The shared secret between the client and the SAFI service.
          type: string
          nullable: false

    MultiFactor:
      description: >
        Specifies a set of authentication Factors in order to establish
        the identity of a Subject.
      type: object
      nullable: false
      example:
        gsid: "00000000-0000-0000-0000-000000000000"
        factors:
        - using: otp
          factor: "789903"
        - using: password
          factor: "the quick yellow penguin slid in the lazy dogs dms"
      required:
      - gsid
      - factors
      properties:
        gsid:
          description: >
            A Global Subject Identifier (GSID) specifying the Subject to which
            this Factor is applicable.
          type: string
          format: uuid
        factors:
          description: >
            The Factors to use in establishing the identity of the Subject specified
            by `gsid`. The `gsid` member on individual Factor instances is ignored.
          type: array
          items:
            x-qsa-exclude-fields:
            - gsid
            $ref: "#/components/schemas/Factor"

    SharedSecret:
      type: object
      nullable: false
      example:
        link: "otpauth://hotp/Secure%20App:alice%40google.com?secret=JBSWY3DPEHPK3PXP&issuer=Secure%20App&counter=0"
      required:
      - link
      properties:
        link:
          description: >
            A link that is recognized by client OTP applications to import the
            shared secret.
          type: string

    Version:
      type: object
      nullable: false
      example:
        version: "1.0.2"
      required:
      - version
      properties:
        version:
          description: >
            The application version that is currently running.
          type: string

    Health:
      type: object
      nullable: false
      example:
        started: 1528573407847
        uptime: 65293
      required:
      - started
      - uptime
      properties:
        started:
          description: >
            Indicates the date and time at which the application instance was
            started, in milliseconds since the UNIX epoch.
          type: integer
          format: int64
        uptime:
          description: >
            Current application instance lifetime, in milliseconds.
          type: integer
          format: int64

    Error:
      type: object
      nullable: false
      example:
        code: "INTERNAL_SERVER_ERROR"
        detail: "An uncaught exception condition interrupted the request-response cycle."
        hint: "Contact the system administrator if the condition persists."
        id: "67dfd969-98ac-4057-b992-92e19f6ea7ac"
      required:
      - code
      - message
      properties:
        code:
          description: >
            Specifies the exception condition that occurred.
          type: string
        message:
          description: >
            Error message targeted at the end-user.
          type: string
        detail:
          description: >
            A message providing a more detailed explanation of the error
            condition that occurred.
          type: string
        hint:
          description: >
            A hint indicating on how to resolve the situation.
          type: string
        id:
          description: >
            An identifier for this specific exception condition, which may be used
            for debugging purposes.
          type: string
          format: uuid

    ServiceNotAvailable:
      type: object
      nullable: false
      example:
        code: "SERVICE_NOT_AVAILABLE"
        detail: "The service is currently not available. Try again later."
        hint: "Cease making requests until after the period indicated in the Retry-After header."
      required:
      - code
      - message
      - detail
      - hint
      properties:
        code:
          description: >
            Specifies the cause of service unavailability.
          type: string
        message:
          description: >
            Error message targeted at the end-user.
          type: string
        detail:
          description: >
            A message providing a more detailed explanation of the reasons
            why the service is not available.
          type: string
        hint:
          description: >
            A hint indicating on how to resolve the situation.
          type: string
