---
#######################################################################
# OpenAPI definition for the  application.
#
# NOTES:
#
# - Endpoints are configured with the `x-endpoint` attribute.
# - Schema definitions of `requestBody`, for any content type,
#   is assumed to be defined in `components` and referenced.
#
#######################################################################
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Subject One-Time Password Service
  description: >
    This service exposes an API to generate, refresh, remove and verify
    One-Time Passwords (OTPs) for Subjects in a Quantum system.
  termsOfService: https://www.wizardsofindustry.net
  contact:
    name: Cochise Ruhulessin
    url: https://www.wizardsofindustry.net/projects/quantum
    email: cochise.ruhulessin@wizardsofindustry.net
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: http://otp.dev.quantumframework.org:8443
  description: Local development server
- url: https://citadel.dev.quantumframework.org/otp
  description: Local development server (Citadel)
paths:
  /health/:
    summary: Reports the general health of the application.
    x-endpoint:
      classname: HealthEndpoint
      controller:
        qualname: sq.ext.health.HealthCheckCtrl
    parameters:
    - name: timeout
      in: query
      description: Specifies the timeout of the health-check, in milliseconds.
      schema:
        type: integer
    get:
      operationId: get_health
      responses:
        200:
          description: The service is functioning normally.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /version:
    summary: Reports the currently running version of the application.
    x-endpoint:
      classname: VersionEndpoint
      controller:
        qualname: sq.ext.health.VersionCtrl
    get:
      operationId: get_version
      responses:
        200:
          description: Details about the current application deployment.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /{kind}:
    summary: >
      Provides an interface to create, regenerate or retrieve the
      One-Time Password (OTP) for the Subject identified in the
      request entity.
    x-endpoint:
      classname: OneTimePasswordEndpoint
      controller:
        qualname: otp.app.ctrl.OneTimePasswordCtrl
    parameters:
    - name: kind
      in: path
      required: true
      schema:
        type: string
        enum:
        - totp
        - hotp
    get:
      operationId: getotp
      parameters:
      - name: gsid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      summary: Retrieve the currently configured shared secret for a Subject.
      responses:
        200:
          description: >
            An OTP exists for the Subject identified in the request URI and
            the shared secret is returned to the client.
          content:
            image/png:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                $ref: "#/components/schemas/SharedSecret"
        404:
          description: >
            The Subject identified in the request URI does not
            exist.
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"
    post:
      operationId: createotp
      summary: Generate a new OTP for the Subject identified in the request entity.
      requestBody:
        description: >
          This endpoint expects the Global Subject Identifier (GSID), the Issuer
          name and a Natural Subject Identifier (NSID) to be present in the
          request body.
        content:
          application/json:
            schema:
              required:
              - gsid
              - nsid
              - issuer
              properties:
                gsid:
                  type: string
                  format: uuid
                nsid:
                  type: string
                issuer:
                  type: string
      responses:
        201:
          description: >
            A new OTP is generated for the identified Subject.
          content:
            image/png:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                $ref: "#/components/schemas/SharedSecret"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"
    put:
      operationId: createotp
      summary: >
        Regenerate an existing OTP for the Subject identified in the
        request entity.
      requestBody:
        description: >
          This endpoint expects the Global Subject Identifier (GSID), the Issuer
          name and a Natural Subject Identifier (NSID) to be present in the
          request body.
        content:
          application/json:
            schema:
              required:
              - gsid
              - nsid
              - issuer
              properties:
                gsid:
                  type: string
                  format: uuid
                nsid:
                  type: string
                issuer:
                  type: string
      responses:
        201:
          description: >
            A new OTP is generated for the identified Subject.
          content:
            image/png:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                $ref: "#/components/schemas/SharedSecret"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /verify/{kind}:
    summary: >
      Verifies a One-Time Password (OTP) for a Subject.
    x-endpoint:
      classname: VerificationEndpoint
      controller:
        qualname: otp.app.ctrl.VerificationCtrl
    parameters:
    - name: kind
      in: path
      description: >
        Specifies the type of OTP (totp hotp).
      required: true
      schema:
        type: string
    post:
      operationId: verify
      requestBody:
        description: >
          This endpoint expects the Global Subject Identifier (GSID) and
          a One-Time Password (OTP) to be present in the request body.
        content:
          application/json:
            schema:
              required:
              - gsid
              - code
              properties:
                gsid:
                  type: string
                  format: uuid
                code:
                  type: string
      responses:
        200:
          description: >
            An OTP exists for the Subject identified in the request entity
            and the provided value was correct.
        401:
          description: >
            An OTP exists for this Subject but the value provided in the
            request entity did not match.
        403:
          description: >
            An OTP exists for this Subject but it has been blocked for
            use as an authentication mechanism.
        404:
          description: >
            The Subject identified in the request entity does not
            exist.
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

components:
  responses:
    ServiceNotAvailable:
      description: One or more (upstream) dependencies is not available.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ServiceNotAvailable"

    UncaughException:
      description: An uncaught exception condition interrupted the request-response cycle.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    SharedSecret:
      type: object
      nullable: false
      example:
        link: "otpauth://hotp/Secure%20App:alice%40google.com?secret=JBSWY3DPEHPK3PXP&issuer=Secure%20App&counter=0"
      required:
      - link
      properties:
        link:
          description: >
            A link that is recognized by client OTP applications to import the
            shared secret.
          type: string

    Version:
      type: object
      nullable: false
      example:
        version: "1.0.2"
      required:
      - version
      properties:
        version:
          description: >
            The application version that is currently running.
          type: string

    Health:
      type: object
      nullable: false
      example:
        started: 1528573407847
        uptime: 65293
      required:
      - started
      - uptime
      properties:
        started:
          description: >
            Indicates the date and time at which the application instance was
            started, in milliseconds since the UNIX epoch.
          type: integer
          format: int64
        uptime:
          description: >
            Current application instance lifetime, in milliseconds.
          type: integer
          format: int64

    Error:
      type: object
      nullable: false
      example:
        code: "INTERNAL_SERVER_ERROR"
        detail: "An uncaught exception condition interrupted the request-response cycle."
        hint: "Contact the system administrator if the condition persists."
        id: "67dfd969-98ac-4057-b992-92e19f6ea7ac"
      required:
      - code
      - message
      properties:
        code:
          description: >
            Specifies the exception condition that occurred.
          type: string
        message:
          description: >
            Error message targeted at the end-user.
          type: string
        detail:
          description: >
            A message providing a more detailed explanation of the error
            condition that occurred.
          type: string
        hint:
          description: >
            A hint indicating on how to resolve the situation.
          type: string
        id:
          description: >
            An identifier for this specific exception condition, which may be used
            for debugging purposes.
          type: string
          format: uuid

    ServiceNotAvailable:
      type: object
      nullable: false
      example:
        code: "SERVICE_NOT_AVAILABLE"
        detail: "The service is currently not available. Try again later."
        hint: "Cease making requests until after the period indicated in the Retry-After header."
      required:
      - code
      - message
      - detail
      - hint
      properties:
        code:
          description: >
            Specifies the cause of service unavailability.
          type: string
        message:
          description: >
            Error message targeted at the end-user.
          type: string
        detail:
          description: >
            A message providing a more detailed explanation of the reasons
            why the service is not available.
          type: string
        hint:
          description: >
            A hint indicating on how to resolve the situation.
          type: string
