"""Contains the base class for :class:`OneTimePasswordCtrl`."""
import ioc
from sq.ctrl import EndpointCtrl

class BaseOneTimePasswordCtrl(EndpointCtrl):
    """Generated by SG to serve as an abstract base class for:

        otp.app.ctrl.OneTimePasswordCtrl

    This class encapsulates external dependencies (such as the inversion-of-control
    requirements) and specifies the interface for the concrete implementation.
    """
    otp = ioc.class_property('OneTimePasswordService')
    image = ioc.class_property('QuickResponseImageService')
    finder = ioc.class_property('OneTimePasswordFinder')

    async def post(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`OneTimePasswordCtrl.post()`
        and should be implemented in the following file:

            ./otp/ctrl/onetimepassword/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")

    async def put(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`OneTimePasswordCtrl.put()`
        and should be implemented in the following file:

            ./otp/ctrl/onetimepassword/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")

    async def get(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`OneTimePasswordCtrl.get()`
        and should be implemented in the following file:

            ./otp/ctrl/onetimepassword/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")


#pylint: skip-file
# !!! SG MANAGED FILE -- DO NOT EDIT -- VERSION:  !!!
