"""Add onetimepasswords.enabled column

Revision ID: 60359a8ea0b2
Revises: 6f21fa0d453e
Create Date: 2018-08-16 21:36:38.915391

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '60359a8ea0b2'
down_revision = '6f21fa0d453e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onetimepasswords', sa.Column('enabled', sa.String(),
        server_default=sa.literal(False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onetimepasswords', 'enabled')
    # ### end Alembic commands ###
