"""Change column type to boolean

Revision ID: a8eb8a00d632
Revises: 60359a8ea0b2
Create Date: 2018-08-21 21:45:01.950775

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = 'a8eb8a00d632'
down_revision = '60359a8ea0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
